In [18]:
import os
import json

import pandas as pd
import numpy as np

In [ ]:
os.chdir("..")

# Parameters

In [25]:
antibiotic_dictionary_file = open("data/antibiotics.json", "r")
antibiotic_dictionary = json.load(antibiotic_dictionary_file)
labels = antibiotic_dictionary["Escherichia coli"]

bin_size = 40

In [11]:
file = "data/unprocessed/raw/e_coli_driams.csv"

bac = pd.read_csv(file)
bac

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,...,Clindamycin,Ceftriaxone,Cefepime,Piperacillin-Tazobactam,Meropenem,Imipenem,Tobramycin,Fusidic acid,Oxacillin,Vancomycin
0,743.500000,883.000000,971.666667,1057.500000,1049.0,1002.000000,724.500000,811.333333,803.000000,821.333333,...,NaN,1.0,1.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN
1,112.500000,109.666667,128.500000,86.666667,130.5,90.500000,102.666667,109.000000,86.500000,102.000000,...,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2,1711.000000,1624.500000,1555.000000,1746.500000,1680.5,1663.333333,1969.000000,1975.500000,1976.000000,1995.500000,...,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
3,512.333333,472.000000,448.666667,400.000000,480.0,471.666667,401.500000,496.000000,512.333333,537.000000,...,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
4,715.000000,674.500000,620.333333,568.000000,634.0,614.000000,676.500000,733.333333,898.500000,798.500000,...,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4946,2222.000000,2153.500000,2246.666667,2446.500000,2612.5,2556.666667,2431.000000,2214.000000,2059.000000,1915.500000,...,NaN,1.0,0.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN
4947,3573.500000,2845.333333,2552.500000,2577.000000,2605.5,2646.000000,2469.000000,2439.000000,2494.666667,2516.500000,...,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
4948,0.000000,0.000000,144.000000,182.666667,247.0,231.500000,243.666667,175.000000,154.666667,128.000000,...,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
4949,58.000000,31.000000,52.500000,70.000000,63.5,99.000000,105.666667,91.000000,78.666667,104.500000,...,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
4950,61.000000,55.000000,60.333333,72.000000,38.0,47.000000,34.500000,67.666667,71.500000,65.333333,...,NaN,1.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN

# Binning

In [13]:
malditof = bac[bac.columns.drop(list(bac.filter(regex='[^0-9]')))]
malditof

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,...,9990,9991,9992,9993,9994,9995,9996,9997,9998,9999
0,743.500000,883.000000,971.666667,1057.500000,1049.0,1002.000000,724.500000,811.333333,803.000000,821.333333,...,220.0,160.5,100.0,131.0,180.0,115.0,91.0,123.0,139.0,34.541475
1,112.500000,109.666667,128.500000,86.666667,130.5,90.500000,102.666667,109.000000,86.500000,102.000000,...,237.0,225.0,196.5,192.0,239.0,261.0,206.0,249.0,231.0,108.593585
2,1711.000000,1624.500000,1555.000000,1746.500000,1680.5,1663.333333,1969.000000,1975.500000,1976.000000,1995.500000,...,536.0,508.0,526.0,621.0,561.0,518.0,574.0,488.0,522.0,175.325443
3,512.333333,472.000000,448.666667,400.000000,480.0,471.666667,401.500000,496.000000,512.333333,537.000000,...,867.0,1047.0,956.0,943.0,1085.0,1066.0,1020.0,842.0,879.0,291.948352
4,715.000000,674.500000,620.333333,568.000000,634.0,614.000000,676.500000,733.333333,898.500000,798.500000,...,111.0,146.0,165.0,108.0,112.0,143.0,106.0,91.0,97.0,37.174491
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4946,2222.000000,2153.500000,2246.666667,2446.500000,2612.5,2556.666667,2431.000000,2214.000000,2059.000000,1915.500000,...,42.0,42.0,26.0,47.0,37.0,34.0,71.0,54.0,44.0,8.802848
4947,3573.500000,2845.333333,2552.500000,2577.000000,2605.5,2646.000000,2469.000000,2439.000000,2494.666667,2516.500000,...,63.0,59.0,60.0,75.0,97.0,112.5,78.0,90.0,87.0,27.154554
4948,0.000000,0.000000,144.000000,182.666667,247.0,231.500000,243.666667,175.000000,154.666667,128.000000,...,2.0,1.0,2.0,0.0,0.0,0.0,2.0,2.0,0.0,0.836455
4949,58.000000,31.000000,52.500000,70.000000,63.5,99.000000,105.666667,91.000000,78.666667,104.500000,...,99.0,107.0,133.0,151.0,135.0,154.0,174.0,135.0,160.0,42.870570
4950,61.000000,55.000000,60.333333,72.000000,38.0,47.000000,34.500000,67.666667,71.500000,65.333333,...,152.0,161.0,196.0,234.0,178.0,167.0,239.0,232.0,303.0,38.760745

In [14]:
binned_malditof = malditof.T.groupby(np.arange(len(malditof.columns)) // bin_size).mean().T
binned_malditof.columns = [col for col in range(int(malditof.columns[0]), int(malditof.columns[-1]), bin_size)]
binned_malditof

,2000,2040,2080,2120,2160,2200,2240,2280,2320,2360,...,9600,9640,9680,9720,9760,9800,9840,9880,9920,9960
0,884.900000,975.241667,964.679167,931.591667,998.362500,746.183333,692.562500,650.487500,559.733333,584.662500,...,370.5875,374.4875,567.2250,1952.5000,741.0750,428.3500,347.3875,301.8625,230.1625,157.251037
1,104.666667,181.241667,151.675000,119.412500,165.633333,99.291667,89.220833,79.533333,73.054167,106.125000,...,1088.3875,1146.0875,3460.7875,1133.5500,548.4875,516.7625,344.7875,365.7250,273.3125,232.052340
2,1934.362500,1784.441667,2200.008333,2101.354167,2963.970833,1787.075000,2253.212500,2677.395833,2304.483333,2226.270833,...,1839.8875,2238.5125,8941.1750,3800.4375,1655.0750,1421.9625,1018.3875,938.0250,557.3500,512.770636
3,499.762500,507.175000,620.575000,579.866667,866.783333,566.966667,651.700000,697.604167,690.258333,676.641667,...,2026.5750,2036.7000,3533.1500,8874.7875,4879.3375,3178.6500,2364.9250,2047.4750,1579.7000,1027.011209
4,757.695833,725.683333,854.654167,845.258333,1081.870833,826.300000,946.050000,958.441667,829.512500,734.420833,...,345.8250,294.2625,542.3750,437.4250,211.4125,168.8625,136.3875,152.9375,136.4125,116.979362
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4946,2368.391667,3006.737500,3017.016667,2908.341667,3049.812500,2363.712500,2415.425000,1566.945833,1421.741667,1279.304167,...,356.2125,238.8250,193.9000,472.1000,180.0250,87.2500,69.0250,54.9500,45.5375,42.620071
4947,2956.670833,3362.325000,3274.925000,2549.033333,3054.404167,2149.354167,2043.620833,2098.925000,1652.125000,1565.825000,...,279.7750,251.2250,221.3000,335.4375,205.8875,119.3375,106.6750,103.7000,91.9000,81.978864
4948,192.195833,353.433333,313.954167,225.770833,394.087500,209.704167,166.404167,118.258333,104.562500,132.420833,...,30.2750,11.4375,5.8625,4.5500,2.3875,2.0250,1.6375,2.3375,2.9750,1.108411
4949,81.687500,75.879167,94.450000,81.550000,150.320833,78.037500,78.750000,67.970833,84.695833,85.887500,...,761.1750,942.4125,2801.5875,1092.8125,622.5125,513.5625,278.4250,218.6500,150.2875,134.984264
4950,65.591667,76.287500,160.441667,79.404167,326.933333,74.937500,76.250000,61.954167,84.408333,88.120833,...,1148.6625,1968.1625,9025.6125,2240.6250,1247.8625,1007.3875,568.6500,384.7000,191.3500,177.656519

In [15]:
binned_bac = pd.DataFrame(np.column_stack([binned_malditof, bac[labels]]))
binned_bac.columns = list(binned_malditof.columns) + labels
binned_bac

,2000,2040,2080,2120,2160,2200,2240,2280,2320,2360,...,9760,9800,9840,9880,9920,9960,Ciprofloxacin,Ceftriaxone,Piperacillin-Tazobactam,Cefepime
0,884.900000,975.241667,964.679167,931.591667,998.362500,746.183333,692.562500,650.487500,559.733333,584.662500,...,741.0750,428.3500,347.3875,301.8625,230.1625,157.251037,0.0,1.0,0.0,1.0
1,104.666667,181.241667,151.675000,119.412500,165.633333,99.291667,89.220833,79.533333,73.054167,106.125000,...,548.4875,516.7625,344.7875,365.7250,273.3125,232.052340,0.0,0.0,0.0,0.0
2,1934.362500,1784.441667,2200.008333,2101.354167,2963.970833,1787.075000,2253.212500,2677.395833,2304.483333,2226.270833,...,1655.0750,1421.9625,1018.3875,938.0250,557.3500,512.770636,0.0,0.0,0.0,0.0
3,499.762500,507.175000,620.575000,579.866667,866.783333,566.966667,651.700000,697.604167,690.258333,676.641667,...,4879.3375,3178.6500,2364.9250,2047.4750,1579.7000,1027.011209,0.0,0.0,0.0,0.0
4,757.695833,725.683333,854.654167,845.258333,1081.870833,826.300000,946.050000,958.441667,829.512500,734.420833,...,211.4125,168.8625,136.3875,152.9375,136.4125,116.979362,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4946,2368.391667,3006.737500,3017.016667,2908.341667,3049.812500,2363.712500,2415.425000,1566.945833,1421.741667,1279.304167,...,180.0250,87.2500,69.0250,54.9500,45.5375,42.620071,1.0,1.0,1.0,0.0
4947,2956.670833,3362.325000,3274.925000,2549.033333,3054.404167,2149.354167,2043.620833,2098.925000,1652.125000,1565.825000,...,205.8875,119.3375,106.6750,103.7000,91.9000,81.978864,1.0,0.0,0.0,0.0
4948,192.195833,353.433333,313.954167,225.770833,394.087500,209.704167,166.404167,118.258333,104.562500,132.420833,...,2.3875,2.0250,1.6375,2.3375,2.9750,1.108411,0.0,0.0,0.0,0.0
4949,81.687500,75.879167,94.450000,81.550000,150.320833,78.037500,78.750000,67.970833,84.695833,85.887500,...,622.5125,513.5625,278.4250,218.6500,150.2875,134.984264,0.0,0.0,0.0,0.0
4950,65.591667,76.287500,160.441667,79.404167,326.933333,74.937500,76.250000,61.954167,84.408333,88.120833,...,1247.8625,1007.3875,568.6500,384.7000,191.3500,177.656519,1.0,1.0,0.0,1.0

# Saving File

In [ ]:
file_name_ext = os.path.basename(file)
file_name = os.path.splitext(file_name_ext)[0]
ext = os.path.splitext(file_name_ext)[1]
new_file_name = "data/unprocessed/binned/"+file_name+"_bin"+str(bin_size)+ext

binned_bac.to_csv(new_file_name, index=False, mode='w')